stages:
  - build
  - test
  - security-sast
  - package
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

before_script:
  - echo "=== D√©but du job ==="

after_script:
  - echo "=== Fin du job ==="

# =========================
# üî® BUILD
# =========================
build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - target/

# =========================
# üß™ TEST
# =========================
test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS test
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/*.xml
    paths:
      - target/surefire-reports

# =========================
# üîê SNYK SAST
# =========================
snyk_scan:
  stage: security-sast
  image:
    name: snyk/snyk:maven
    entrypoint: [""]
  script:
    - snyk auth "$SNYK_TOKEN"
    - snyk test --severity-threshold=low
  allow_failure: true

# =========================
# üì¶ PACKAGE
# =========================
package:
  stage: package
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.war

# =========================
# üöÄ DEPLOY
# =========================
deploy:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "D√©ploiement du WAR sur Tomcat..."
    - curl -u "$TOMCAT_USER:$TOMCAT_PASS" -T target/demo-0.0.1-SNAPSHOT.war "https://unswabbed-brenton-unregained.ngrok-free.dev/manager/text/deploy?path=/demo&update=true"
  allow_failure: false
